name: Build Image and run
description: Builds a Docker Image and starts it as a container
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Container
      run: docker build . --file Dockerfile -t vuln_app

    - name: Run Container
      run: docker run -p 80:80 -d vuln_app

    - name: Wait for server to start
      run: sleep 5

