name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Image
      run: sudo docker build . --file Dockerfile -t vuln_app
    - run: sudo docker image ls

    # todo run tests
    # todo run security scans

    - name: Login to Docker Hub
      # if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Image to Docker Hub
      run: sudo docker push jakob999/vuln_app:latest

