name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # todo run tests
    # todo run security scans

    - name: Login to Docker Hub
      # if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.7.0
      with:
        context: .
        push: true
        tags: jakob999/vuln_app:latest


