# Writing comment to trigger pipeline
name: Scan GitHub Actions configuration

on:
  schedule:
    - cron: '0 0 * * 1'
  push:
      paths:
        - '.github/workflows/**'


jobs:
  contract_test:
    runs-on: ubuntu-latest
    environment: build-test-scan
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 15

      - name: Install snyk-iac-rules
        run: npm i -g snyk-iac-rules

      - name: Build bundle
        run: snyk-iac-rules build .

      - name: Run contract with Snyk to check Infrastructure as Code files for issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --rules=bundle.tar.gz