name: Test and Scanning workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Container
        run: docker build . --file Dockerfile -t vuln_app

      - name: Run Container
        run: docker run -p 80:80 -d vuln_app

      - name: Wait for server to start
        run: sleep 5

      - name: Test if container is reachable
        run: curl http://localhost:80