name: Test and Scanning workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Container
        run: docker build . --file Dockerfile -t vuln_app

      - name: Run Container
        run: docker run -p 80:80 -d vuln_app

      - name: Wait for server to start
        run: sleep 5

      - name: Test if container is reachable
        run: curl http://localhost:80

      # Container Scan
      - name: Run Trivy vulnerablility scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: 'vuln_app'
          format: json

  sast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Bearer CLI
        uses: bearer/bearer-action@v2
        with:
          format: json
          scanner: secrets
          output: secrets_bearer.json

      - name: Upload Output
        uses: actions/upload-artifact@v3
        with:
          name: bearer-output
          path: secrets_bearer.json

#  dependency_scan:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Run Aikido
#        uses: AikidoSec/github-actions-workflow@v1.0.13
#        with:
#          secret-key: ${{ secrets.AIKIDO_TOKEN }}
#          minimum-severity: 'HIGH'

#  secret_scan:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Run TruffleHog
#        uses: trufflesecurity/trufflehog@v3.81.9
